const ID='199wvnwyG6tojUhXrIYvX_eXaBoFZ5lBp2YqR0SYG-KU',CHAVE='TROQUE-POR-A-MESMA-CHAVE-QUE-VOCE-JA-USA',FUSO='America/Sao_Paulo',ABA_MENSALIDADES='Mensalidades',ABA_HISTORICO='Histórico Cobranças',ABA_MORADORES='Moradores',CACHE_CONSULTA='consulta_mes_atual_v8';
function out(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function ok(c){if(!c||c!==CHAVE)throw Error('Chave inválida')}
function brl(v){let p=Number(v||0).toFixed(2).split('.');return'R$ '+p[0].replace(/\B(?=(\d{3})+(?!\d))/g,'.')+','+p[1]}
function dv(v){return v instanceof Date&&!isNaN(v.getTime())}
function dt(v){return dv(v)?Utilities.formatDate(v,FUSO,'dd/MM/yyyy'):''}
function dh(v){return dv(v)?Utilities.formatDate(v,FUSO,'dd/MM/yyyy HH:mm'):''}
function ct(v){return dv(v)?Utilities.formatDate(v,FUSO,'MM/yyyy'):String(v||'')}
function ck(v){return dv(v)?Utilities.formatDate(v,FUSO,'yyyy-MM'):String(v||'')}
function limpa(){CacheService.getScriptCache().remove(CACHE_CONSULTA)}
function doGet(e){try{let p=e&&e.parameter?e.parameter:{};ok(p.chave);if(p.acao==='fila')return out(fila_());if(p.acao==='status')return out(status_());if(p.acao==='consulta')return out(consulta_());if(p.acao==='historico')return out(historico_(p.codigo));if(p.acao==='health')return out(health_());if(p.acao==='moradores')return out(moradores_());if(p.acao==='templates')return out(templates_());if(p.acao==='anual')return out(anual_(p.ano));throw Error('Ação inválida')}catch(x){return out({ok:false,erro:String(x.message||x)})}}
function doPost(e){try{let p=JSON.parse(e&&e.postData&&e.postData.contents?e.postData.contents:'{}');ok(p.chave);if(p.acao==='marcar')return out(marcar_(p));if(p.acao==='registrar_pagamento')return out(registrarPagamento_(p));if(p.acao==='anexar_comprovante')return out(anexarComprovante_(p));if(p.acao==='salvar_morador')return out(salvarMorador_(p));if(p.acao==='salvar_templates')return out(salvarTemplates_(p));if(p.acao==='backup')return out(backupAgora_());if(p.acao==='ativar_backup')return out(ativarBackup_());throw Error('Ação inválida')}catch(x){return out({ok:false,erro:String(x.message||x)})}}
function health_(){let s=SpreadsheetApp.openById(ID);return{ok:true,versao:'8.2',planilha:s.getName(),timestamp:dh(new Date())}}
function contextoAtual_(){let ss=SpreadsheetApp.openById(ID),s=ss.getSheetByName(ABA_MENSALIDADES);if(!s)throw Error('Aba Mensalidades não encontrada');let u=s.getLastRow();if(u<4)return{ss:ss,sheet:s,dados:[]};let atual=Utilities.formatDate(new Date(),FUSO,'yyyy-MM'),c=s.getRange(4,2,u-3,1).getValues(),ini=-1,fim=-1;c.forEach(function(r,i){if(ck(r[0])===atual){if(ini<0)ini=i+4;fim=i+4}});if(ini<0)return{ss:ss,sheet:s,dados:[]};let v=s.getRange(ini,1,fim-ini+1,25).getValues();return{ss:ss,sheet:s,dados:v.map(function(r,i){return{linha:ini+i,row:r}})}}
function rank_(a){a=String(a||'').toUpperCase();if(a.indexOf('2ª')>=0)return 1;if(a.indexOf('1ª')>=0)return 2;if(a==='VENCE HOJE')return 3;if(a==='LEMBRETE')return 4;return 5}
function chaveH(c,comp,a){return[String(c||'').trim(),ck(comp),String(a||'').trim().toUpperCase()].join('|')}
function enviadosHoje(ss){let z=new Set(),h=ss.getSheetByName(ABA_HISTORICO);if(!h||h.getLastRow()<4)return z;let hoje=Utilities.formatDate(new Date(),FUSO,'yyyy-MM-dd');h.getRange(4,1,h.getLastRow()-3,8).getValues().forEach(function(r){if(dv(r[0])&&Utilities.formatDate(r[0],FUSO,'yyyy-MM-dd')===hoje&&String(r[6]||'').toUpperCase()==='ENVIADO')z.add(chaveH(r[1],r[3],r[4]))});return z}
function aplicarTemplate_(t,r){return String(t||'').replace(/\[nome\]/gi,r[3]).replace(/\[competencia\]/gi,ct(r[1])).replace(/\[valor\]/gi,brl(r[10])).replace(/\[vencimento\]/gi,dt(r[5]))}
function mensagem_(r){let a=String(r[13]||'').toUpperCase(),ts=templates_().templates,t=a==='LEMBRETE'?ts.lembrete:a==='VENCE HOJE'?ts.vence_hoje:a.indexOf('1ª')>=0?ts.primeira:a.indexOf('2ª')>=0?ts.segunda:'';if(t)return aplicarTemplate_(t,r);if(String(r[17]||'').trim())return String(r[17]).trim();return aplicarTemplate_(ts.primeira,r)}
function fila_(){let x=contextoAtual_(),hist=enviadosHoje(x.ss),f=[],ven=0,lem=0,total=0,ag=new Date();x.dados.forEach(function(i){let r=i.row,m=r[3],t=r[4],st=String(r[12]||'').trim().toUpperCase(),a=String(r[13]||'').trim(),prx=r[15],saldo=Number(r[10]||0),se=String(r[21]||'').trim().toUpperCase();if(!m||!t||st==='PAGO'||saldo<=0||!a||se==='ENVIADO')return;if(se==='ADIADO'&&dv(prx)&&prx>ag)return;if(hist.has(chaveH(r[2],r[1],a)))return;let p=rank_(a);if(p<=2)ven++;if(a.toUpperCase()==='LEMBRETE')lem++;total+=saldo;f.push({linha:i.linha,codigo:r[2],morador:m,telefone:t,competencia:ct(r[1]),saldo:brl(saldo),acao:a,mensagem:mensagem_(r),prioridade:p})});f.sort(function(a,b){return a.prioridade-b.prioridade||a.morador.localeCompare(b.morador,'pt-BR')});return{ok:true,fila:f,qtd:f.length,vencidas:ven,lembretes:lem,total_aberto:brl(total)}}
function status_(){let r=fila_();return{ok:true,qtd:r.qtd,vencidas:r.vencidas,lembretes:r.lembretes,total_aberto:r.total_aberto,assinatura:r.fila.map(function(x){return x.linha+'-'+x.codigo+'-'+x.acao}).join('|')}}
function forma_(v){v=String(v||'').trim();return['PIX','DINHEIRO','TRANSFERENCIA','BOLETO','CARTAO','OUTRO'].indexOf(v.toUpperCase())>=0?v:''}
function consulta_(){let cache=CacheService.getScriptCache(),g=cache.get(CACHE_CONSULTA);if(g)return JSON.parse(g);let x=contextoAtual_(),pg=[],pd=[],tp=0,td=0,prev=0,comp='';x.dados.forEach(function(i){let r=i.row;if(!r[3])return;comp=comp||ct(r[1]);let devido=Number(r[6]||0),pago=Number(r[9]||0),saldo=Number(r[10]||0),st=String(r[12]||'').trim().toUpperCase(),b={linha:i.linha,codigo:r[2],morador:r[3],telefone:r[4]};prev+=devido;tp+=pago;if(st==='PAGO'||saldo<=0){b.valor_pago=brl(pago);b.data_pagamento=dt(r[11]);b.forma_pagamento=forma_(r[20]);pg.push(b)}else{b.saldo=brl(saldo);b.vencimento=dt(r[5]);b.mensagem=mensagem_(r);pd.push(b);td+=saldo}});pg.sort(function(a,b){return a.morador.localeCompare(b.morador,'pt-BR')});pd.sort(function(a,b){return a.morador.localeCompare(b.morador,'pt-BR')});let r={ok:true,competencia:comp,total_moradores:pg.length+pd.length,qtd_pagos:pg.length,qtd_pendentes:pd.length,total_previsto:brl(prev),total_pago:brl(tp),total_pendente:brl(td),pagos:pg,pendentes:pd};cache.put(CACHE_CONSULTA,JSON.stringify(r),30);return r}
function historico_(codigo){let ss=SpreadsheetApp.openById(ID),h=ss.getSheetByName(ABA_HISTORICO),z=[];if(!h||h.getLastRow()<4)return{ok:true,historico:z};let u=h.getLastRow(),ini=Math.max(4,u-499);h.getRange(ini,1,u-ini+1,8).getValues().forEach(function(r){if(String(r[1])===String(codigo))z.push({data:dh(r[0]),competencia:ct(r[3]),tipo:String(r[4]||''),canal:String(r[5]||''),resultado:String(r[6]||''),observacao:String(r[7]||'')})});z.reverse();return{ok:true,historico:z}}
function data_(t){let m=String(t||'').match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(!m)throw Error('Data inválida. Use dd/mm/aaaa.');let d=new Date(+m[3],+m[2]-1,+m[1]);if(d.getFullYear()!==+m[3]||d.getMonth()!==+m[2]-1||d.getDate()!==+m[1])throw Error('Data inválida.');return d}
function registrarPagamento_(p){let lock=LockService.getScriptLock();lock.waitLock(10000);try{let x=contextoAtual_(),cod=String(p.codigo||''),valor=Number(p.valor||0),forma=forma_(p.forma),data=data_(p.data),obs=String(p.observacao||'').trim();if(!cod)throw Error('Morador inválido.');if(!(valor>0))throw Error('O valor deve ser maior que zero.');if(!forma)throw Error('Forma de pagamento inválida.');let i=x.dados.find(function(a){return String(a.row[2])===cod});if(!i)throw Error('Morador não encontrado na competência atual.');let r=i.row,saldo=Number(r[10]||0),pago=Number(r[9]||0);if(saldo<=0)throw Error('Esta mensalidade já está paga.');if(valor>saldo+.001)throw Error('Valor maior que o saldo de '+brl(saldo)+'.');let novo=pago+valor,resta=Math.max(0,saldo-valor),quitado=resta<.01,h=x.ss.getSheetByName(ABA_HISTORICO);if(!h)throw Error('Aba Histórico Cobranças não encontrada.');x.sheet.getRange(i.linha,10).setValue(novo);x.sheet.getRange(i.linha,12).setValue(data);x.sheet.getRange(i.linha,22).setValue(quitado?'ENVIADO':'AGUARDANDO');x.sheet.getRange(i.linha,25).clearContent();if(quitado)x.sheet.getRange(i.linha,21).setValue(forma);let texto='Pagamento de '+brl(valor)+' em '+dt(data)+' via '+forma+(obs?' — '+obs:'');let atual=String(r[19]||'').trim();x.sheet.getRange(i.linha,20).setValue(atual?atual+'\n'+texto:texto);h.appendRow([new Date(),r[2],r[3],r[1],'PAGAMENTO',forma,quitado?'PAGO':'PARCIAL',texto]);SpreadsheetApp.flush();limpa();return{ok:true,status:quitado?'PAGO':'PARCIAL',valor_pago:brl(valor),saldo:brl(resta)}}finally{lock.releaseLock()}}
function marcar_(p){let lock=LockService.getScriptLock();lock.waitLock(10000);try{let ss=SpreadsheetApp.openById(ID),s=ss.getSheetByName(ABA_MENSALIDADES),h=ss.getSheetByName(ABA_HISTORICO),l=Number(p.linha);if(!s||!h)throw Error('Abas obrigatórias não encontradas');if(!l||l<4)throw Error('Linha inválida');let r=s.getRange(l,1,1,25).getValues()[0],z=String(p.resultado||'').trim().toUpperCase(),ag=new Date(),a=String(r[13]||'').trim(),hist=enviadosHoje(ss);if(z==='ENVIADO'&&hist.has(chaveH(r[2],r[1],a)))return{ok:true,duplicado:true};if(z==='ENVIADO'){s.getRange(l,15).setValue(ag);s.getRange(l,17).setValue(Number(r[16]||0)+1);s.getRange(l,22).setValue('ENVIADO');s.getRange(l,24).setValue(ag);s.getRange(l,25).clearContent()}else if(z==='ADIAR_1_DIA'){let d=new Date(ag);d.setDate(d.getDate()+1);s.getRange(l,16).setValue(d);s.getRange(l,22).setValue('ADIADO');s.getRange(l,25).setValue('Adiado 1 dia pelo aplicativo.')}else if(z==='PAGO'){s.getRange(l,22).setValue('PAGAMENTO INFORMADO');s.getRange(l,25).setValue('Use Registrar pagamento para confirmar valor e data.')}else{s.getRange(l,22).setValue(z);if(z==='ERRO')s.getRange(l,25).setValue('Retentativa necessária.')}h.appendRow([ag,r[2],r[3],r[1],a,'WhatsApp',z,String(p.observacao||'Aplicativo v8.2')]);SpreadsheetApp.flush();limpa();return{ok:true}}finally{lock.releaseLock()}}
function templates_(){let p=PropertiesService.getScriptProperties(),d={lembrete:'Olá [nome], tudo bem? A Associação de Moradores informa que a contribuição referente a [competencia], no valor de [valor], vencerá em [vencimento]. Agradecemos pela colaboração.',vence_hoje:'Olá [nome], tudo bem? A contribuição da Associação de Moradores referente a [competencia], no valor de [valor], vence hoje. Agradecemos pela colaboração.',primeira:'Olá [nome], tudo bem? A contribuição referente a [competencia], no valor de [valor], permanece em aberto desde [vencimento]. Caso já tenha pago, desconsidere e nos informe. Obrigado.',segunda:'Olá [nome]. Reforçamos que a contribuição referente a [competencia], no valor de [valor], continua pendente. Pedimos a gentileza de regularizar ou entrar em contato. Obrigado.',agradecimento:'Olá [nome], recebemos seu pagamento de [valor] referente a [competencia]. Muito obrigado pela colaboração com a Associação de Moradores!'};Object.keys(d).forEach(function(k){d[k]=p.getProperty('tpl_'+k)||d[k]});return{ok:true,templates:d}}
function salvarTemplates_(p){let t=p.templates||{},pr=PropertiesService.getScriptProperties();['lembrete','vence_hoje','primeira','segunda','agradecimento'].forEach(function(k){if(String(t[k]||'').trim())pr.setProperty('tpl_'+k,String(t[k]).trim())});return{ok:true}}
function moradores_(){let s=SpreadsheetApp.openById(ID).getSheetByName(ABA_MORADORES),z=[];if(!s)throw Error('Aba Moradores não encontrada');if(s.getLastRow()<4)return{ok:true,moradores:z};s.getRange(4,1,s.getLastRow()-3,4).getValues().forEach(function(r,i){if(r[0]||r[1])z.push({linha:i+4,codigo:r[0],nome:r[1],telefone:r[2],situacao:String(r[3]||'Ativo')})});return{ok:true,moradores:z}}
function salvarMorador_(p){let lock=LockService.getScriptLock();lock.waitLock(10000);try{let s=SpreadsheetApp.openById(ID).getSheetByName(ABA_MORADORES);if(!s)throw Error('Aba Moradores não encontrada');let cod=String(p.codigo||'').trim(),nome=String(p.nome||'').trim(),tel=String(p.telefone||'').trim(),sit=String(p.situacao||'Ativo').trim();if(!nome||!tel)throw Error('Informe nome e telefone.');let linha=Number(p.linha||0);if(!linha){let dados=s.getLastRow()>=4?s.getRange(4,1,s.getLastRow()-3,1).getValues():[],maior=0;dados.forEach(function(r){maior=Math.max(maior,Number(r[0]||0))});cod=cod||String(maior+1);linha=Math.max(4,s.getLastRow()+1)}s.getRange(linha,1,1,4).setValues([[cod,nome,tel,sit]]);SpreadsheetApp.flush();limpa();return{ok:true,linha:linha,codigo:cod}}finally{lock.releaseLock()}}
function anual_(ano){ano=Number(ano||Utilities.formatDate(new Date(),FUSO,'yyyy'));let s=SpreadsheetApp.openById(ID).getSheetByName(ABA_MENSALIDADES),meses=[];for(let m=1;m<=12;m++)meses.push({mes:m,competencia:(m<10?'0':'')+m+'/'+ano,previsto:0,pago:0,pendente:0,qtd_pagos:0,qtd_pendentes:0});if(!s||s.getLastRow()<4)return{ok:true,ano:ano,meses:meses};s.getRange(4,1,s.getLastRow()-3,25).getValues().forEach(function(r){if(!dv(r[1])||r[1].getFullYear()!==ano||!r[3])return;let x=meses[r[1].getMonth()];x.previsto+=Number(r[6]||0);x.pago+=Number(r[9]||0);x.pendente+=Number(r[10]||0);if(String(r[12]||'').toUpperCase()==='PAGO'||Number(r[10]||0)<=0)x.qtd_pagos++;else x.qtd_pendentes++});meses.forEach(function(x){x.previsto=brl(x.previsto);x.pago=brl(x.pago);x.pendente=brl(x.pendente)});return{ok:true,ano:ano,meses:meses}}
function backupAgora_(){let arq=DriveApp.getFileById(ID),nome='Backup_Associacao_'+Utilities.formatDate(new Date(),FUSO,'yyyy-MM-dd_HH-mm');let copia=arq.makeCopy(nome);return{ok:true,nome:copia.getName(),url:copia.getUrl()}}
function executarBackupDiario(){backupAgora_()}
function ativarBackup_(){ScriptApp.getProjectTriggers().forEach(function(t){if(t.getHandlerFunction()==='executarBackupDiario')ScriptApp.deleteTrigger(t)});ScriptApp.newTrigger('executarBackupDiario').timeBased().everyDays(1).atHour(2).create();return{ok:true,mensagem:'Backup diário ativado para aproximadamente 02:00.'}}
function anexarComprovante_(p){let ss=SpreadsheetApp.openById(ID),h=ss.getSheetByName(ABA_HISTORICO),cod=String(p.codigo||''),nome=String(p.morador||''),arquivo=String(p.arquivo||'').trim(),obs=String(p.observacao||'').trim();if(!h)throw Error('Aba Histórico Cobranças não encontrada.');if(!cod||!arquivo)throw Error('Morador ou arquivo inválido.');let comp=new Date();try{let x=contextoAtual_(),i=x.dados.find(function(a){return String(a.row[2])===cod});if(i){comp=i.row[1];let atual=String(i.row[19]||'').trim(),texto='Comprovante anexado: '+arquivo+(obs?' — '+obs:'');x.sheet.getRange(i.linha,20).setValue(atual?atual+'\n'+texto:texto)}}catch(e){}h.appendRow([new Date(),cod,nome,comp,'COMPROVANTE','Arquivo local','ANEXADO','Comprovante: '+arquivo+(obs?' — '+obs:'')]);SpreadsheetApp.flush();return{ok:true}}
